// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/katherinekim/MainGit/fellow/redwood-intro/web/src/pages/FatalErrorPage/FatalErrorPage'
import NotFoundPageType from '/Users/katherinekim/MainGit/fellow/redwood-intro/web/src/pages/NotFoundPage/NotFoundPage'
import UserBalancePageType from '/Users/katherinekim/MainGit/fellow/redwood-intro/web/src/pages/UserBalancePage/UserBalancePage'
import PostEditPostPageType from '/Users/katherinekim/MainGit/fellow/redwood-intro/web/src/pages/Post/EditPostPage/EditPostPage'
import PostNewPostPageType from '/Users/katherinekim/MainGit/fellow/redwood-intro/web/src/pages/Post/NewPostPage/NewPostPage'
import PostPostPageType from '/Users/katherinekim/MainGit/fellow/redwood-intro/web/src/pages/Post/PostPage/PostPage'
import PostPostsPageType from '/Users/katherinekim/MainGit/fellow/redwood-intro/web/src/pages/Post/PostsPage/PostsPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const NotFoundPage: typeof NotFoundPageType
  const UserBalancePage: typeof UserBalancePageType
  const PostEditPostPage: typeof PostEditPostPageType
  const PostNewPostPage: typeof PostNewPostPageType
  const PostPostPage: typeof PostPostPageType
  const PostPostsPage: typeof PostPostsPageType
}
