// This file was generated by RedwoodJS
import * as Cell from './UserBalanceCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindUserBalanceQuery, FindUserBalanceQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './UserBalanceCell'

type CellInputs = CellProps<SuccessType, FindUserBalanceQuery, typeof Cell, FindUserBalanceQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
